from django.urls import path, include
from .views import (
    admin_view,
    projects_view,
    # add_project_view,
    admin_bursaries_view,
    add_bursary_view,
    admin_reports_view,
    admin_projects_view,
    add_project_view,
    # add_citizen_report_view,
    apply_bursary_view,
    citizen_report_view,
    home_view,
    # add_citizen_report_view,
    delete_report_view,
    delete_bursary_view,
    delete_project_view,
    edit_bursary_view,
    edit_project_view,
    edit_report_view
)


urlpatterns = [
    path('', home_view, name='home'),
    path('ng_cdf/admin/dashboard', admin_view, name='dashboard'),
    path('ng_cdf/admin/add/projects', add_project_view, name='add-projects'),
    path('ng_cdf/admin/view/reports', admin_reports_view, name='reports'),
    path('ng_cdf/admin/view/projects', admin_projects_view, name='projects'),
    path('ng_cdf/citizen/reports', citizen_report_view, name='citizen-reports'),
    path('ng_cdf/admin/add/bursary', add_bursary_view, name='add-bursary'),
    path('ng_cdf/citizen/apply/bursary/<int:bursary_id>', apply_bursary_view, name='apply-bursary'),
    path('ng_cdf/admin/delete/report/<int:report_id>', delete_report_view, name='delete-report'),
    path('ng_cdf/admin/delete/bursary/<int:bursary_id>', delete_bursary_view, name='delete-bursary'),
    path('ng_cdf/admin/delete/project/<int:project_id>', delete_project_view, name='delete-project'),
    path('ng_cdf/admin/edit/bursary/<int:bursary_id>', edit_bursary_view, name='edit-bursary'),
    path('ng_cdf/admin/edit/project/<int:project_id>', edit_project_view, name='edit-project'),
    path('ng_cdf/admin/edit/report/<int:report_id>', edit_report_view, name='edit-report'),
    path('ng_cdf/admin/view/projects', projects_view, name='projects'),
    # path('ng_cdf/citizen/add/report', add_citizen_report_view, name='add-report'),
    # path('ng_cdf/admin/add/project', add_project_view, name='add-project'),
    # path('ng_cdf/admin/add/bursary', add_bursary_view, name='add-bursary'),
    # path('ng_cdf/admin/add/report', add_citizen_report_view, name='add-report'),
    path('ng_cdf/admin/view/bursaries/<str:status>', admin_bursaries_view, name='bursaries'),
]
